swagger: '2.0'
info:
  description: API
  version: 1.0.0
  title: Inventarios API
  # put the contact info for your development or API team
  contact:
    email: jhosepchai@gmail.com

  license:
    name: GNU GPL 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html

# tags are used for organizing operations
tags:
- name: Usuarios
- name: Niveles
- name: Departamentos
- name: Proveedores



paths:
  /Usuarios/listar:
    get:
      tags:
      - Usuarios
      summary: Lista usuarios
      operationId: listarUsuarios
      description: |
        Al hacer la peticion sin parametros se devolvera una lista de objetos de usuarios
      produces:
      - application/json

      security:
      - api_key: []
      
      responses:
        200:
          description: Devuelve array de usuarios activos
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        400:
          description: bad input parameter
          
  /Usuarios/login:
    post:
      tags:
      - Usuarios
      summary: Login de usuario
      description: Permite al usuario hacer login
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: itemLogin
        description: Datos correctos para hacer login
        schema:
          $ref: '#/definitions/user_login'
      responses:
        200:
          description: peticion correcta
          
     
        404:
          description: invalid input, object invalid
          
          
  /Niveles/crear:
    post:
      tags:
      - Niveles
      summary: Agregar un nuevo nivel
      description: Agregar un nuevo nivel de usuario
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: NivelItem
        description: Item de nivel a agregar
        schema:
          $ref: '#/definitions/NewNivel'

      security:
      - api_key: []

      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/NivelItem'
              
  /Niveles/eliminar/{_id}:
    delete:
      tags:
      - Niveles
      summary: Eliminar un  nivel
      description: Eliminar un  nivel de usuario
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: _id
        in: path
        description: ID del nivel a eliminar
        required: true
        type: string
      
      security:
      - api_key: []
        
      
      responses:
        200:
          description: OK
  
  /Niveles/actualizar:
    put:
      tags:
      - Niveles
      summary: Actualiza un  nivel
      description: Actualizar un  nivel de usuario
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Nivel item
        description: Item de nivel a actualizar
        schema:
          $ref: '#/definitions/NewNivel'
      security:
      - api_key: []
      
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/NivelItem'
          
  /Niveles/listar:
    get:
      tags:
      - Niveles
      summary: Listar todos niveles
      description: Listar todos nivel de usuario
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - api_key: []
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/NivelItem'
          
    
    
    
  /Departamentos/listar:
    get:
      tags:
      - Departamentos
      summary: Listar todos Departamentos
      description: Listar todos Departamentos del Pais
      consumes:
      - application/json
      produces:
      - application/json
      
      security:
      - api_key: []
      
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/Departamentos'
  
  /Proveedores/listar:
    get:
      tags:
      - Proveedores
      summary: Listar todos los proveedores
      description: Listar todos los proveedores existentes
      consumes:
      - application/json
      produces:
      - application/json

      security:
      - api_key: []
    
      
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/Proveedores'
  
  /Proveedores/crear:
    post:
      tags:
      - Proveedores
      summary: Agregar nuevo proveedor
      description: Agregar un nuevo proveedor
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Proveedores
        description: Items de proveedor a agregar
        schema:
          $ref: '#/definitions/NewProveedor'
      security:
      - api_key: []
      
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/Proveedores'

  /Proveedores/actualizar:
    put:
      tags:
      - Proveedores
      summary: Actualizar proveedor
      description: Actualizar un proveedor
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Proveedores
        description: Items de proveedor a actualizar
        schema:
          $ref: '#/definitions/UpdateProveedor'
      
      security:
      - api_key: []

      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/Proveedores'  
  
  /Proveedores/eliminar/{_id}:
    delete:
      tags:
      - Proveedores
      summary: Eliminar un proveedor
      description: Eliminar un  proveedor
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: _id
        in: path
        description: ID del proveedor a eliminar
        required: true
        type: string
      security:
      - api_key: []
      
      responses:
        200:
          description: OK

  /Sucursales/crear:
    post:
      tags:
      - Sucursales
      summary: Agregar una nueva sucursal
      description: Agregar una nueva sucursal con su respectiva bodega
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: Sucursales
        description: Items de sucursal con bodega a agregar
        schema:
          $ref: '#/definitions/NewSucursal_Bodega'
      security:
      - api_key: []
      responses:
        200:
          description: OK
          schema :
            type : array
            items:
              $ref : '#/definitions/Bodega'


securityDefinitions:
  api_key:
    type: "apiKey"
    name: "access-token"
    in: "header"


definitions:
  user_login:
    type: object
    required:
    - usuario
    - password
    - name
    - lastname
    - createAt
    - token
    - estado
    
    properties:
      usuario:
        type: string
        example: jhosepIslam
      password:
        type: string
        example: 123 
    
  User:
    type: object
    properties:
      id:
        type: object
      usuario:
        type: string
      name:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      createdAt:
        type: string
      estado:
        type: boolean
      
    xml:
      name: User
      
  NivelItem:
    type: object
    properties:
      _id:
        type: object
      Estado:
        type: boolean
      Tipo:
        type: string
      Numero:
        type: number
    xml:
      name: Nivel
    
    
  NewNivel:
    type: object
    properties:
      id:
        type: object
      Tipo:
        type: string
      Numero:
        type: number
    xml:
      name: NewNivel
    
  Departamentos:
    type: object
    properties:
      Departamento:
        type: string
      Municipios:
        type: array
        items:
          type: string
          minItems: 5
            
            
          
          
    xml:
      name: Departamentos

  
  Proveedores:
    type: object
    properties:
      _id:
        type: object
      Nombre:
        type: string
      Razon_Social:
        type: string
      Contacto:
        type: object
        properties:
          Direccion:
            type: object
            properties:
              Departamento: 
                type: string
              Municipio:
                type: string
              Detalle:
                type: string
          Telefono:
            type: string
          Correo:
            type: string
      Estado:
        type: boolean
    xml:
      name: Proveedores
  
  NewProveedor:
    type: object
    properties:
      Nombre:
        type: string
      Razon_Social:
        type: string
      Departamento:
        type: string
      Municipio:
        type: string
      Descripcion:
        type: string
      Telefono:
        type: string
      Correo:
        type: string
    xml:
      name: NewProveedores

  UpdateProveedor:
    type: object
    properties:
      id:
        type: object
      Nombre:
        type: string
      Razon_Social:
        type: string
      Departamento:
        type: string
      Municipio:
        type: string
      Descripcion:
        type: string
      Telefono:
        type: string
      Correo:
        type: string
    xml:
      name: UpdateProveedor
  
  NewSucursal_Bodega:
    type: object
    properties:
      Nombre:
        type: string
      Codigo:
        type: number
      Departamento:
        type: string
      Municipio:
        type: string
      Descripcion:
        type: string
      Telefono:
        type: string
      Correo:
        type: string
      Largo:
        type: number
      Ancho:
        type: number
      Estanterias:
        type: number
    
    xml:
      name: NewSucursal_Bodega
      
  Bodega:
    type: object
    properties:
      Sucursal:
        type: object
        properties:
          Nombre:
            type: string
          Codigo:
            type: number
          Contacto:
            type: object
            properties:
              Direccion:
                type: object
                properties:
                  Departamento:
                    type: string
                  Municipio:
                    type: string
                  Descripcion:
                    type: string
              
              Telefono: 
                type: string
              Correo: 
                type: string
          Estado:
            type: boolean
      NumeroBodega:
        type: number
      Estanterias:
        type: number
      Largo:
        type: number
      Ancho:
        type: number
      Estado:
        type: boolean
        
    xml:
      name: Bodega
      
      
host: localhost:3000
basePath: /api
schemes:
 - http
 - https